In [10]:
import torch

x = torch.arange(0,32)
print(x)
x = x.reshape(1,4,8)
print(x)
x = x.reshape(1,4,4,2)
print(x)
x = x.transpose(1,2)
print(x)
x = x.reshape(1,4,8)
print(x)


tensor([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
        18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31])
tensor([[[ 0,  1,  2,  3,  4,  5,  6,  7],
         [ 8,  9, 10, 11, 12, 13, 14, 15],
         [16, 17, 18, 19, 20, 21, 22, 23],
         [24, 25, 26, 27, 28, 29, 30, 31]]])
tensor([[[[ 0,  1],
          [ 2,  3],
          [ 4,  5],
          [ 6,  7]],

         [[ 8,  9],
          [10, 11],
          [12, 13],
          [14, 15]],

         [[16, 17],
          [18, 19],
          [20, 21],
          [22, 23]],

         [[24, 25],
          [26, 27],
          [28, 29],
          [30, 31]]]])
tensor([[[[ 0,  1],
          [ 8,  9],
          [16, 17],
          [24, 25]],

         [[ 2,  3],
          [10, 11],
          [18, 19],
          [26, 27]],

         [[ 4,  5],
          [12, 13],
          [20, 21],
          [28, 29]],

         [[ 6,  7],
          [14, 15],
          [22, 23],
          [30, 31]]]])
tensor([[[ 0,  1,  8,  